version: '3.9'

services:
  postgres14_read1:
    image: postgres:14
    container_name: postgres14_read1
    networks:
      read1_net:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0
      - POSTGRES_DB=read1
    volumes:
      - postgres14_read1_data:/var/lib/postgresql/data

networks:
  read1_net:
    driver: bridge

volumes:
  postgres14_read1_data:
