server:
  servlet:
    context-path: /api/read1/
  port: ${PORT:8080}

spring:
  profiles:
    active: "her"
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username:
    password:

  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    initialization-mode: always
#    schema: classpath:schema.sql
#    data: classpath:db/data.sql

    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/read4}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:0}

  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

jwt:
  expiration: 15

#host-url: http://localhost:8080/read1
host-url:  http://18.156.192.31/read1
host: http://18.156.192.31

